# Generated Dockerfile for modalix Build:release[2.1.2]

FROM debian:bookworm

# List of additional packages that are to be deployed in SDK sysroot
ARG SDK_PKG_LIST
ENV SDK_PKG_LIST="\
	libgrpc-dev,\
	protobuf-compiler-grpc,\
	python3-pybind11,\
	${SDK_PKG_LIST}"

RUN dpkg --add-architecture arm64
RUN dpkg --add-architecture arc
RUN dpkg --add-architecture armhf
RUN apt-get clean && \
    apt-get update --allow-releaseinfo-change && \
    apt-get install -y wget pip
RUN wget -qO - https://mirror.elxr.dev/elxr/public.gpg | gpg --dearmor -o /etc/apt/trusted.gpg.d/elxr.gpg
RUN wget -qO - https://packages.fluentbit.io/fluentbit.key | gpg --dearmor > /etc/apt/trusted.gpg.d/fluentbit.gpg
RUN wget --no-check-certificate -O - https://repo.sima.ai/elxr/deb/simaai.gpg | gpg --dearmor > /etc/apt/trusted.gpg.d/simaai.gpg
RUN chmod 644 /etc/apt/trusted.gpg.d/elxr.gpg
RUN chmod 644 /etc/apt/trusted.gpg.d/fluentbit.gpg
RUN chmod 644 /etc/apt/trusted.gpg.d/simaai.gpg

RUN echo "deb [signed-by=/etc/apt/trusted.gpg.d/elxr.gpg] https://mirror.elxr.dev/elxr aria main" > /etc/apt/sources.list.d/elxr.list
RUN echo "deb [signed-by=/etc/apt/trusted.gpg.d/fluentbit.gpg] https://packages.fluentbit.io/debian/bookworm bookworm main" >> /etc/apt/sources.list.d/elxr.list
RUN echo "deb [signed-by=/etc/apt/trusted.gpg.d/simaai.gpg] https://repo.sima.ai/elxr/deb/release bookworm non-free" >> /etc/apt/sources.list.d/elxr.list

RUN apt-get update --allow-releaseinfo-change && \
    apt-get install -y --no-install-recommends \
	python3-apt-ostree \
	vim \
	make \
	cmake \
	gcc-aarch64-linux-gnu \
	g++-aarch64-linux-gnu \
	device-tree-compiler \
	bison \
	flex \
	quilt \
	zlib1g-dev \
	bzip2 \
	bc \
	rsync \
	kmod \
	cpio \
	git \
	curl \
	libssl-dev \
	libgnutls28-dev \
	openssh-client \
	simaai-sdk-tools

RUN echo "Package: *" > /etc/apt/preferences.d/stable.pref
RUN echo "Pin: origin \"repo.sima.ai/elxr\"" >> /etc/apt/preferences.d/stable.pref
RUN echo "Pin-Priority: 999" >> /etc/apt/preferences.d/stable.pref

COPY --chmod=0755 scripts/install-ros2.sh /usr/local/bin/install-ros2
RUN /usr/local/bin/install-ros2

RUN export RUSTUP_HOME=/opt/toolchain/rust && export CARGO_HOME=/opt/toolchain/rust && \
    mkdir -p ${RUSTUP_HOME} && curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/rustup.sh && \
    chmod 755 /tmp/rustup.sh && /tmp/rustup.sh -y && \
    echo "export RUSTUP_HOME=${RUSTUP_HOME}" >> ${CARGO_HOME}/env && \
    echo "export CARGO_HOME=${CARGO_HOME}" >> ${CARGO_HOME}/env && \
    . ${CARGO_HOME}/env && rm /tmp/rustup.sh

RUN if uname -a | grep -q '#[0-9]*-Ubuntu'; then \
        apt-get update --allow-releaseinfo-change; \
        --privileged mount -t binfmt_misc binfmt_misc /proc/sys/fs/binfmt_misc || true; \
    fi

RUN if [ "x86_64" = "x86_64" ]; then apt update --allow-releaseinfo-change && apt install \
    arch-test -y; fi

RUN python3 /opt/bin/simaai_setup_sdk.py modalix 2.1.2 \
	 \
	"${SDK_PKG_LIST}"

COPY --chmod=0755 scripts/install-realsense.sh /usr/local/bin/install-realsense
RUN /usr/local/bin/install-realsense

RUN echo "source /opt/bin/simaai-init-build-env modalix" >> /root/.bashrc
RUN echo "source /usr/local/ros2/local_setup.bash" >> /root/.bashrc && \
    echo "source /usr/local/rosbot_navigation/local_setup.bash" >> /root/.bashrc && \
    echo "source /usr/local/rtabmap-ros/local_setup.bash" >> /root/.bashrc
